---
title: "forudsætningstest model 2 - uden kontrol variabler"
author: "Eva Tryde"
date: "1/5/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, include=FALSE}
library(tidyverse)
library(psych)
library(car)
library(ggpubr)
library(stargazer)
library(broom)
library(ggplot2)
library(performance)
library(see)
library(qqplotr)
library(reshape2)
library(robustbase)
library(estimatr)
library(interplot)
library(ggpubr)
library(lmtest)
library(ggeffects)
library(extrafont)
loadfonts()
library(viridis)
library(patchwork)


```

## Opsætning


```{r data, message=FALSE}
ess <- read.csv("../../data/ess_treated.csv")
auto  <- read.csv("../../data/auto_scale.csv")
rtv_merge <- read_csv("../../../RTV trussel/RTV/data/rtv_merge.csv")
```

```{r, message=FALSE}
rtv_merge <- rtv_merge %>%
  rename(year = merge_year)%>%
  filter(year >= 2002)%>%
  dplyr::select(cntry, year, n_de_mu_im_pop)

rtv_merge$trussel[rtv_merge$n_de_mu_im_pop > 0] <- 1
rtv_merge$trussel[rtv_merge$n_de_mu_im_pop == 0] <- 0
rtv_merge$trussel[is.na(rtv_merge$n_de_mu_im_pop)] <- NA
ess$year<- ess$int.year

flip <- function(x){
  6 - x
}

ess <- mutate_at(ess, .vars=c("livecntr"), flip)
ess$livecntr[ess$brncntr != 2] <- 0

ess <- ess %>%
  dplyr::filter(cntry %in% c(
  "NO", "SE", "DK", "DE", "GB", "IT", "ES", "NL", "AT", "FR", "PT",
  "FI", "GR", "CH", "IE", "BE", "LU", "IS"))%>%
  filter(dikotom == "muslim")%>%
  dplyr::select(essround, id, cntry, mnrgtjb, rlgdgr, year, income, educ.ba, female, age, livecntr)%>%
  mutate(cntry = as.factor(cntry))

samlet_rtv <- left_join(ess, rtv_merge, by = c("cntry", "year"))

auto <- auto %>%
  dplyr::select(id, cntry, PVQ, essround)

samlet_ess <- left_join(samlet_rtv, auto, by =c("id", "cntry", "essround"))
samlet_ess$income[samlet_ess$income %in% c(11,12)] <- NA

samlet_ess$livecntr_f[samlet_ess$livecntr == 0] <- "Født i landet"
samlet_ess$livecntr_f[samlet_ess$livecntr == 1] <- "Mere end 20 år"
samlet_ess$livecntr_f[samlet_ess$livecntr == 2] <- "Mellem 11 og 20 år"
samlet_ess$livecntr_f[samlet_ess$livecntr == 3] <- "Mellem 6 og 10 år"
samlet_ess$livecntr_f[samlet_ess$livecntr %in% c(4,5)] <- "Mellem 0 og 5 år"

samlet_ess$livecntr_f <- as.factor(samlet_ess$livecntr_f)
levels(samlet_ess$livecntr_f)
samlet_ess$livecntr_f = factor(samlet_ess$livecntr_f, levels=c("Mellem 0 og 5 år",  "Mellem 6 og 10 år", "Mellem 11 og 20 år", "Mere end 20 år", "Født i landet"))
levels(samlet_ess$livecntr_f)
```


```{r}
rm(ess, auto, samlet_rtv, rtv_merge)
```

```{r}
lm <- lm(mnrgtjb ~ PVQ*n_de_mu_im_pop + cntry, data = samlet_ess)
lm_rob <- lmrob(mnrgtjb ~ PVQ*n_de_mu_im_pop + cntry, data = samlet_ess, control = lmrob.control(k.max = 500, fast.s.large.n = Inf))
stargazer(lm, lm_rob, type = "text")
```

```{r}
df <- samlet_ess %>%
  filter(!is.na(mnrgtjb) & !is.na(n_de_mu_im_pop) & !is.na(PVQ) & !is.na(cntry))%>%
  dplyr::select(c("PVQ", "mnrgtjb", "n_de_mu_im_pop", "cntry"))
df$fit.r <- lm$residuals
df$fit.p <- lm$fitted.values
```

## Linearitet
kan ikke test, givet interaktion

## Samlet plot

```{r}
png(file="../../figures/forudsætningstest 1 år/model 2 uden kontrol/residualer.png", width = 7.5, height = 4, units = "in", res=500)

r <- residualPlots(lm)
stargazer(r)
print(r)
dev.off()

```

graf 1: linearitet af data

graf 2: Normalitet af fejlled

graf 3: Homogeneity of variance

graf 4: Outliers og indflydelserige observationer\

```{r}
png(file="../../figures/forudsætningstest 1 år/model 2 uden kontrol/plotr.png", width = 7.5, height = 7.5, units = "in", res=500)
par(mfrow = c(2, 2))
plot(lm)
dev.off()

```

## **Heteroskedaslitet**

```{r}
check_heteroscedasticity(lm)
lmtest::bptest(lm)  # Breusch-Pagan test
car::ncvTest(lm)  # NCV test
```

```{r}
png(file="../../figures/forudsætningstest 1 år/model 2 uden kontrol/homoskedadastitet.png", width = 7.5, height = 7.5, units = "in", res=500)
plot <- ggplot(df, aes(fit.p, fit.r)) +
  geom_jitter(shape = 1) +
  geom_hline(yintercept = 0, color = "red") +
  ylab("Residuals") +
  xlab("Fitted")+
  theme_minimal()

plot
dev.off()
plot
```

## Normal fordeling

```{r}
png(file="../../figures/forudsætningstest 1 år/model 2 uden kontrol/normal fordeling.png", width = 7.5, height = 7.5, units = "in", res=500)

p1 <- ggplot(df, aes(fit.r)) +
  geom_histogram(bins = 10, color = "black", fill = "white")

p2 <- ggplot(df, aes(fit.r)) +
  geom_density() +
  stat_function(fun = dnorm, args = list(mean = mean(df$fit.r),
                                         sd = sd(df$fit.r)),
                color = "dodgerblue", size = 2, alpha = .5)

p3 <- ggplot(df, aes("", fit.r)) +
  geom_boxplot() 

p4 <- ggplot(df, aes(sample = fit.r)) +
  stat_qq(shape = 1) +
  stat_qq_line(size = 1.5, alpha = .5)

plot <- ggarrange(p1, p2, p3, p4, nrow = 2, ncol = 2)
plot

dev.off()

plot
```

## Multikollinaritet

```{r}
r <- check_collinearity(lm)
r
png(file="../../figures/forudsætningstest 1 år/model 2 uden kontrol/Multicollinearity.png", width = 7.5, height = 5, units = "in", res=500)
plot(r)
dev.off()

```

## Outliers

```{r}
png(file="../../figures/forudsætningstest 1 år/model 2 uden kontrol/outliers.png", width = 7.5, height = 5, units = "in", res=500)
check_outliers(lm)
plot<- plot(check_outliers(lm))
plot
dev.off()

```

```{r}
png(file="../../figures/forudsætningstest 1 år/model 2 uden kontrol/check model.png", width = 7.5, height = 9, units = "in", res=500)

plot <- check_model(lm)
plot
dev.off()
```

```{r}

```