---
title: "Bilag - A 1 - t-test"
output:
  pdf_document: default
  html_notebook: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, include=FALSE}
library(tidyverse)
library(psych)
library(car)
library(ggpubr)
library(stargazer)
library(broom)
library(ggplot2)
library(performance)
library(see)
library(qqplotr)
library(reshape2)
library(robustbase)
library(estimatr)
library(interplot)
library(ggpubr)
library(lmtest)
library(ggeffects)
library(extrafont)
loadfonts()
library(viridis)
library(patchwork)

```

```{r data, message=FALSE}
ess <- read.csv("../data/ess_treated.csv")
auto  <- read.csv("../data/auto_scale.csv")
```

```{r, message=FALSE}
ess <- ess %>%
  filter(cntry %in% c(
  "NO", "SE", "DK", "DE", "GB", "IT", "ES", "NL", "AT", "FR", "PT",
  "FI", "GR", "CH", "IE", "BE", "LU", "IS"))%>%
  filter(dikotom %in% c("muslim", "majority"))%>%
  dplyr::select(id, cntry, rlgdgr, income, educ.ba, female, age, dikotom, essround)

auto <- auto %>%
  dplyr::select(id, cntry, PVQ, auto_cat, essround)

samlet_ess <- left_join(ess, auto, by =c("id", "cntry", "essround"))

samlet_ess$income[samlet_ess$income %in% c(11,12)] <- NA

rm(ess, auto)
```


## Indkomst niveau
```{r}
#png(file="../figures/t.test/normal.png", width=600, height=350)

samlet_ess_ma <- samlet_ess%>%
  filter(dikotom == "majority")
ma <- ggqqplot(samlet_ess_ma$income,
               title = "Majoritets respondenter",
               ggtheme = theme_minimal())

samlet_ess_mu <- samlet_ess%>%
  filter(dikotom == "muslim")
mu <- ggqqplot(samlet_ess_mu$income,
               title = "Muslimske respondenter",
               ggtheme = theme_minimal())


plot <- ggarrange(ma, mu, nrow = 1)
rm(mu, ma)
plot
#dev.off()
plot

```

```{r}
leveneTest(income ~ dikotom, data = samlet_ess)

ttest <- stats::t.test(income ~ dikotom, data = samlet_ess, var.equal = FALSE)
ttest$statistic
ttest

tapply(samlet_ess$income, samlet_ess$dikotom, mean, na.rm=TRUE)

tapply(samlet_ess$income, samlet_ess$dikotom, sd, na.rm=TRUE)
```
## Uddannelsesniveau
```{r}
#png(file="../figures/t.test/normal.png", width=600, height=350)

samlet_ess_ma <- samlet_ess%>%
  filter(dikotom == "majority")
ma <- ggqqplot(samlet_ess_ma$educ.ba,
               title = "Majoritets respondenter",
               ggtheme = theme_minimal())

samlet_ess_mu <- samlet_ess%>%
  filter(dikotom == "muslim")
mu <- ggqqplot(samlet_ess_mu$educ.ba,
               title = "Muslimske respondenter",
               ggtheme = theme_minimal())


plot <- ggarrange(ma, mu, nrow = 1)
rm(mu, ma)
plot
#dev.off()
plot

```

```{r}
leveneTest(educ.ba ~ dikotom, data = samlet_ess)

ttest <- stats::t.test(educ.ba ~ dikotom, data = samlet_ess, var.equal = FALSE)
ttest$statistic
ttest

tapply(samlet_ess$educ.ba, samlet_ess$dikotom, mean, na.rm=TRUE)

tapply(samlet_ess$educ.ba, samlet_ess$dikotom, sd, na.rm=TRUE)
```

## Religøsitet 
```{r}
#png(file="../figures/t.test/normal.png", width=600, height=350)

samlet_ess_ma <- samlet_ess%>%
  filter(dikotom == "majority")
ma <- ggqqplot(samlet_ess_ma$rlgdgr,
               title = "Majoritets respondenter",
               ggtheme = theme_minimal())

samlet_ess_mu <- samlet_ess%>%
  filter(dikotom == "muslim")
mu <- ggqqplot(samlet_ess_mu$rlgdgr,
               title = "Muslimske respondenter",
               ggtheme = theme_minimal())


plot <- ggarrange(ma, mu, nrow = 1)
rm(mu, ma)
plot
#dev.off()
plot

```

```{r}
leveneTest(rlgdgr ~ dikotom, data = samlet_ess)

ttest <- stats::t.test(rlgdgr ~ dikotom, data = samlet_ess, var.equal = FALSE)

ttest$statistic
ttest

tapply(samlet_ess$rlgdgr, samlet_ess$dikotom, mean, na.rm=TRUE)

tapply(samlet_ess$rlgdgr, samlet_ess$dikotom, sd, na.rm=TRUE)


```


```{r}
df <- samlet_ess %>%
  filter(age > 17 & age < 100)

leveneTest(age ~ dikotom, data = df)

ttest <- stats::t.test(age ~ dikotom, data = df, var.equal = FALSE)

ttest$statistic
ttest

tapply(df$age, df$dikotom, mean, na.rm=TRUE)

tapply(df$age, df$dikotom, sd, na.rm=TRUE)

```

```{r}
leveneTest(female ~ dikotom, data = samlet_ess)

ttest <- stats::t.test(female ~ dikotom, data = samlet_ess, var.equal = FALSE)

ttest$statistic
ttest

tapply(samlet_ess$female, samlet_ess$dikotom, mean, na.rm=TRUE)

tapply(samlet_ess$female, samlet_ess$dikotom, sd, na.rm=TRUE)

```

